homeassistant:
  # Name of the location where Home Assistant is running
  name: Parent's Home
  # Location required to calculate the time the sun rises and sets
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: !secret home_elevation
  # metric for Metric, imperial for Imperial
  unit_system: imperial
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: America/Indiana/Indianapolis
  customize: !include customize.yaml

# Show links to resources in log and frontend
#introduction:

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  api_password: !secret api_password
  #ssl_certificate: !secret ssl_certificate
  #ssl_key: !secret ssl_key
  #base_url: !secret base_url
  #server_port: !secret server_port
  cors_allowed_origins:
    - https://google.com
    - https://home-assistant.io
  use_x_forwarded_for: False
  #trusted_networks:
  #  - !secret trusted_ip
  #ip_ban_enabled: True
  #login_attempts_threshold: 5
  # Uncomment this if you are using SSL or running in Docker etc
  # base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  include_used_components: true

# Discover some devices automatically
discovery:

# Track the sun
sun:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time.
history:

# View all events in a logbook
logbook:

# Enable Map Function
map:

#Presence-detection
device_tracker:
  - platform: nmap_tracker
    hosts: 
      - 192.168.1.31
      - 192.168.1.7
      - 192.168.1.13
    exclude:
      - 192.168.1.1
      - 192.168.1.30
    home_interval: 15
    track_new_devices: no
    consider_home: 300
    interval_seconds: 60
    scan_options: " --privileged -sP "
    # sudo setcap cap_net_raw,cap_net_admin,cap_net_bind_service+eip /usr/bin/nmap 
# - platform: unifi
#  username: !secret unifi_username
#  password: !secret unifi_password
#  host: !secret unifi_host
#  verify_ssl: false
#  track_new_devices: no
#  site_id: !secret unifi_siteid
      
# Using Google for Text to speech
tts:
  platform: google

ifttt:
  key: !secret ifttt_api
 
mqtt:
  broker: 192.168.1.10
#  protocol: 3.1
  keepalive: 60
  port: 1883
  client_id: home-assistant-mqtt
  username: !secret mqtt_user
  password: !secret mqtt_password
  

group: !include groups.yaml
automation: !include automations.yaml
#media_player: !include media_players.yaml
#switch: !include switches.yaml
sensor: !include_dir_list sensors/
#camera: !include cameras.yaml
#input_select: !include inputs/input_select.yaml
#input_slider: !include inputs/input_slider.yaml
#weblink: misc/web_links.yaml
#shell_command: !include shell_commands.yaml
#script: !include scripts.yaml
